### ISSUE TITLE
Add `fmc_file_rules` resource and data source

### ISSUE THREAD

**Issue by teande** [netascode/terraform-provider-fmc#107] opened 2024-07-22 12:55 UTC
API: /api/fmc_config/v1/domain/{DOMAIN_UUID}/policy/filepolicies/{file_policy_id}/filerules

**Comment by mmaciejc** [comment] 2024-10-21 10:41
Duplicate of:
https://github.com/netascode/terraform-provider-fmc/issues/147

**Comment by rchrabas** [comment] 2024-12-11 13:06
Duplicate.

**Closed by rchrabas** 2024-12-11 13:06 UTC
Labels: enhancement
