### ISSUE TITLE
Add `fmc_deploy` resource

### ISSUE THREAD

**Issue by danischm** [netascode/terraform-provider-fmc#56] opened 2024-06-18 16:17 UTC
API: /api/fmc_config/v1/domain/{domainUUID}/deployment/deploymentrequests

Probably similar approach as with this (https://github.com/CiscoDevNet/terraform-provider-iosxe/blob/4e008a455996c4df7a721186d33f270273d37e0e/internal/provider/resource_iosxe_save_config.go#L59) resource and an internal attribute that always changes to force updates.

**Comment by jabielecki** [comment] 2024-07-16 17:33
duplicate of 87

**Closed by jabielecki** 2024-07-16 17:33 UTC
Labels: enhancement
